spring:
  active:
    profiles: local
server:
  port: 8081
---
spring:
  active:
    profiles: dev
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: newuser
    password: password
    driver-class-name: org.postgresql.Driver
jwt:
  secret: gymappomgitsyoungsheldon
  expiration: 3600000
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
---
spring:
  active:
    profiles: stg
server:
  port: 9000
---
spring:
  active:
    profiles: prod
server:
  port: 8000
