spring.application.name=workload-service
spring.data.mongodb.uri=mongodb://localhost:27017/workload-service
server.port=0
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.instance.preferIpAddress=true